/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef TIME_H
#define TIME_H

/* function declarations */
void init_Time(void);
Netsnmp_Node_Handler handle_GetTime;

#endif /* TIME_H */
