/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "Time.h"
#include <time.h>

/** Initializes the Time module */
void
init_Time(void)
{
    const oid GetTime_oid[] = { 1,3,6,1,4,1,310,3,1 };

  DEBUGMSGTL(("Time", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("GetTime", handle_GetTime,
                               GetTime_oid, OID_LENGTH(GetTime_oid),
                               HANDLER_CAN_RONLY
        ));
}

int
handle_GetTime(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    time_t t;
    switch(reqinfo->mode) {

        case MODE_GET:
        time(&t);
        char sztime[100];
        snprintf(sztime,100,"%s",ctime(&t));
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     /* XXX: a pointer to the scalar's data */
                                     sztime,
                                     /* XXX: the length of the data in bytes */
                                     strlen(sztime));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_GetTime\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

static int keep_running;
RETSIGTYPE stop_server(int __attribute__((unused)) a) {
        keep_running = 0;
}

int main()
{
   const char *app_name = "Time";
   /* we are a subagent */
   netsnmp_ds_set_boolean(NETSNMP_DS_APPLICATION_ID, NETSNMP_DS_AGENT_ROLE, 1);

   /* initialize the agent library */
   init_agent(app_name);

   /* initialize your mib code here */
   init_Time();

   /* Time will be used to read Time.conf files. */
   init_snmp("Time");
   keep_running = 1;
   while(keep_running)
   {
        agent_check_and_process(1);/* block every 1 second */
   }
   /* at shutdown time */
   snmp_shutdown(app_name);

   /* deinitialize your mib code here */

   /* shutdown the agent library */
   shutdown_agent();
   return 0;
}
