/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef WLANID_H
#define WLANID_H

/* function declarations */
void init_wlanID(void);
Netsnmp_Node_Handler handle_wlanID;

#endif /* WLANID_H */
