/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef MACSTA_H
#define MACSTA_H

/* function declarations */
void init_macSTA(void);
Netsnmp_Node_Handler handle_macSTA;

#endif /* MACSTA_H */
