/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "nodeHost.h"
#include "common.h"

/** Initializes the nodeHost module */
void
init_nodeHost(void)
{
    const oid nodeHost_oid[] = { 1,3,6,1,4,1,8072,2,4,1,1,1 };

  DEBUGMSGTL(("nodeHost", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("nodeHost", handle_nodeHost,
                               nodeHost_oid, OID_LENGTH(nodeHost_oid),
                               HANDLER_CAN_RONLY
        ));
}

int
handle_nodeHost(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    char node_host[100];
    char buf[30];
 
    memset(buf, 0, sizeof(buf)); 
    strcpy(buf, "hostname");
    memset(node_host, 0, sizeof(node_host));

    switch(reqinfo->mode) {

        case MODE_GET:
            get_info(node_host, buf);
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     node_host,
                                     strlen(node_host));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_nodeHost\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
