/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "numberSTA.h"
#include "common.h"

/** Initializes the numberSTA module */
void
init_numberSTA(void)
{
    const oid numberSTA_oid[] = { 1,3,6,1,4,1,8072,2,4,1,1,8 };

  DEBUGMSGTL(("numberSTA", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("numberSTA", handle_numberSTA,
                               numberSTA_oid, OID_LENGTH(numberSTA_oid),
                               HANDLER_CAN_RONLY
        ));
}
/*convert the string to integer numbers*/
// static int 
// str_to_int(char *str)
// {
//     int sum = 0;
//     int i;
//     for (i = 0; i < strlen(str); ++i)
//     {
//        sum = sum * 10 + str[i] - '0';
//        // printf("%c\n", str[i]);
//     }
//     return sum;
// }

int
handle_numberSTA(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    char num_sta[100];
    char buf[30];
    int number_sta = 0;
 
    memset(buf, 0, sizeof(buf)); 
    strcpy(buf, "Number");
    memset(num_sta, 0, sizeof(num_sta));
  
    switch(reqinfo->mode) {

        case MODE_GET:
            get_info(num_sta, buf);
            // printf("haha,%s\n", num_sta);
            sscanf(num_sta, "%d", &number_sta);
            // number_sta = str_to_int(num_sta);
            // printf("%d\n", number_sta);
            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                     &number_sta,
                                     sizeof(int));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_numberSTA\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
