/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef NUMBERSTA_H
#define NUMBERSTA_H

/* function declarations */
void init_numberSTA(void);
Netsnmp_Node_Handler handle_numberSTA;

#endif /* NUMBERSTA_H */
