/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef ETHMACADRR_H
#define ETHMACADRR_H

/* function declarations */
void init_ethMacAdrr(void);
Netsnmp_Node_Handler handle_ethMacAdrr;

#endif /* ETHMACADRR_H */
