/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "macSTA.h"
#include "common.h"

/** Initializes the macSTA module */
void
init_macSTA(void)
{
    const oid macSTA_oid[] = { 1,3,6,1,4,1,8072,2,4,1,1,9 };

  DEBUGMSGTL(("macSTA", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("macSTA", handle_macSTA,
                               macSTA_oid, OID_LENGTH(macSTA_oid),
                               HANDLER_CAN_RONLY
        ));
}

/*
This fuction read the node.txt file,find the 
STA string,spilte it and join them in snmp_str string.
input : STA1:\tec:55:f9:8b:51:40
        STA2:\tec:55:f9:8b:51:40
output: ec:55:f9:8b:51:40\tec:55:f9:8b:51:40

*/
static void
get_sta_mac(char snmp_str[], char buf[], char rem[])
{
       FILE *fp;
       char temp[100];
       char filename[128];
       char remtemp[30];
       char *s;
       char *t;
       char *p;

       memset(filename, 0, sizeof(filename));
       strcpy(filename, "/tmp/node.txt");

       if ((fp = fopen(filename, "r")) != NULL)
        {
            while(fgets(temp, sizeof(temp), fp) != NULL)
            {
                /*Check if temp has buf*/
                s = strstr(temp, buf);
                p = strstr(temp, rem);
                if ( s != NULL && p == NULL)
                {
                    /*return substring of temp*/
                    t = strtok(temp, "\t");
                    while(t)
                    {
                       // sprintf(snmp_str, "%s", t);
                       strcpy(remtemp, t);
                       t = strtok(NULL, "\t");
                     }  
                    if (remtemp[strlen(remtemp) - 1] == '\n')
                    {
                        remtemp[strlen(remtemp) - 1] = '\t';
                    }
                    strcat(snmp_str, remtemp);       
                    // break;
                }
            }  

            /*The fgets return '\n',so just remove it*/ 
            if (snmp_str[strlen(snmp_str) - 1] == '\t')
            {
                snmp_str[strlen(snmp_str) - 1] = '\0';
            }  
            printf("%s\n", snmp_str);      
            fclose(fp);                     
        }
        else
        {
             perror("Can't open file");
        }
}

int
handle_macSTA(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    char mac_sta[255];
    char buf[30];
    char rem[30];
 
    memset(buf, 0, sizeof(buf)); 
    memset(rem, 0, sizeof(rem));
    strcpy(buf, "STA");
    strcpy(rem, "Number");
    memset(mac_sta, 0, sizeof(mac_sta));

    switch(reqinfo->mode) {

        case MODE_GET:
            get_sta_mac(mac_sta, buf, rem);
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     mac_sta,
                                     strlen(mac_sta));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_macSTA\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
