/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef NETTYPE_H
#define NETTYPE_H

/* function declarations */
void init_netType(void);
Netsnmp_Node_Handler handle_netType;

#endif /* NETTYPE_H */
