/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef WLANSSID_H
#define WLANSSID_H

/* function declarations */
void init_wlanSSID(void);
Netsnmp_Node_Handler handle_wlanSSID;

#endif /* WLANSSID_H */
