/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "wlanMacAdrr.h"
#include "common.h"

/** Initializes the wlanMacAdrr module */
void
init_wlanMacAdrr(void)
{
    const oid wlanMacAdrr_oid[] = { 1,3,6,1,4,1,8072,2,4,1,1,3 };

  DEBUGMSGTL(("wlanMacAdrr", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("wlanMacAdrr", handle_wlanMacAdrr,
                               wlanMacAdrr_oid, OID_LENGTH(wlanMacAdrr_oid),
                               HANDLER_CAN_RONLY
        ));
}

int
handle_wlanMacAdrr(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    char wlan_macaddr[100];

    char buf[30];

    memset(buf, 0, sizeof(buf)); 
    strcpy(buf, "wlan");
    memset(wlan_macaddr, 0, sizeof(wlan_macaddr));


    switch(reqinfo->mode) {

        case MODE_GET:
            get_info(wlan_macaddr, buf);
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     wlan_macaddr,
                                     strlen(wlan_macaddr));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_wlanMacAdrr\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
