/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef MYTIME_H
#define MYTIME_H

/* function declarations */
void init_myTime(void);
Netsnmp_Node_Handler handle_myTime;

#endif /* MYTIME_H */
