/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <stdlib.h>
#include <fcntl.h>
#include <error.h>
#include "wlanID.h"

/** Initializes the wlanID module */
void
init_wlanID(void)
{
    const oid wlanID_oid[] = { 1,3,6,1,4,1,8072,2,4,1,1,1 };

  DEBUGMSGTL(("wlanID", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("wlanID", handle_wlanID,
                               wlanID_oid, OID_LENGTH(wlanID_oid),
                               HANDLER_CAN_RONLY
        ));
}

int
handle_wlanID(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    int fd;
    char sztime[100];
    char filename[128];
    char buf[64];

    if (getcwd(buf, sizeof(buf)-1) == NULL)
        perror("error");
     
    memset(filename, 0, sizeof(filename));
    strcat(filename, buf);
    // printf("%s\n", filename);
    strcat(filename, "/apinfo");
    // printf("%s\n", filename);
    switch(reqinfo->mode) {

        case MODE_GET:
            // snprintf(sztime,100,"%s",ctime(&t));
            // printf("hello world!\n");
             system("iw dev wlan0 link > apinfo");
            // printf("hello world!\n");
            if ((fd = fopen(filename, "rw")) != NULL)
            {
                 //read(fd, sztime, 55);
                fgets(buf, 50, fd);
                // printf("hello world!\n");
                if (fgets(sztime, 100, fd) == NULL)
                {
                    break;
                }
                if (sztime[strlen(sztime) - 1] == '\n')
                {
                    sztime[strlen(sztime) - 1] = 0;              /*replace newline with null*/
                }     
                printf("%s\n", sztime);     
                fclose(fd);                     
            }
            else
            {
                perror("Can't open file");
            }
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     /* XXX: a pointer to the scalar's data */
                                    sztime,
                                     /* XXX: the length of the data in bytes */
                                    strlen(sztime));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_wlanID\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
