/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef DESTANDNEXTMACADDR_H
#define DESTANDNEXTMACADDR_H

/* function declarations */
void init_destAndNextMacAddr(void);
Netsnmp_Node_Handler handle_destAndNextMacAddr;

#endif /* DESTANDNEXTMACADDR_H */
