/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <stdlib.h>
#include <fcntl.h>
#include "ethMacAdrr.h"
#include "common.h"

/** Initializes the ethMacAdrr module */
void
init_ethMacAdrr(void)
{
    const oid ethMacAdrr_oid[] = { 1,3,6,1,4,1,8072,2,4,1,1,4 };

  DEBUGMSGTL(("ethMacAdrr", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("ethMacAdrr", handle_ethMacAdrr,
                               ethMacAdrr_oid, OID_LENGTH(ethMacAdrr_oid),
                               HANDLER_CAN_RONLY
        ));
}

int
handle_ethMacAdrr(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    char eth_macaddr[100];
    memset(eth_macaddr, 0, sizeof(eth_macaddr));
    switch(reqinfo->mode) {

        case MODE_GET:

            get_info(eth_macaddr, "eth0");
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     eth_macaddr,
                                     strlen(eth_macaddr));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_ethMacAdrr\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
