/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <stdlib.h>
#include <fcntl.h>
#include "nodeHost.h"

/** Initializes the nodeHost module */
void
init_nodeHost(void)
{
    const oid nodeHost_oid[] = { 1,3,6,1,4,1,8072,2,4,1,1,1 };

  DEBUGMSGTL(("nodeHost", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("nodeHost", handle_nodeHost,
                               nodeHost_oid, OID_LENGTH(nodeHost_oid),
                               HANDLER_CAN_RONLY
        ));
}

int
handle_nodeHost(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    FILE *fp;
    char node_host[100];
    char temp[100];
    char filename[128];
    char buf[30];
    char *s;
    char *t;

    memset(filename, 0, sizeof(filename));
    strcpy(filename, "/home/buddy/work/snmp/topoinfo/node.txt");
    memset(buf, 0, sizeof(buf)); 
    strcpy(buf, "hostname");
    memset(node_host, 0, sizeof(node_host));

    switch(reqinfo->mode) {

        case MODE_GET:
            if ((fp = fopen(filename, "r")) != NULL)
            {
                while(fgets(temp, sizeof(temp), fp) != NULL)
                {
                    /*Check if temp has buf*/
                    s = strstr(temp, buf);
                    if ( s != NULL)
                    {
                        t = strtok(temp, "\t");
                        while(t)
                        {
                           // sprintf(snmp_str, "%s", t);
                           strcpy(node_host, t);
                           t = strtok(NULL, "\t");

                           /*NOTE: if the below line run, segment fault comes*/
                           // strcpy(snmp_str, t);
                         }  
                         break;
                    }
                }
                // /*Check if temp has buf*/
                // if (s != NULL)
                // {
                //     /*The fgets return '\n',so just remove it*/
                //     if (temp[strlen(temp) - 1] == '\n')
                //     {
                //         temp[strlen(temp) - 1] = '\0';
                //     }  
                //     strcpy(node_host, temp);
                //     printf("%s\n", node_host);  
                // }      
                fclose(fp);                     
            }
            else
            {
                perror("Can't open file");
            }

            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     node_host,
                                     strlen(node_host));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_nodeHost\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
