/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <stdlib.h>
#include <fcntl.h>
#include "destAndNextMacAddr.h"

/** Initializes the destAndNextMacAddr module */
void
init_destAndNextMacAddr(void)
{
    const oid destAndNextMacAddr_oid[] = { 1,3,6,1,4,1,8072,2,4,1,1,5 };

  DEBUGMSGTL(("destAndNextMacAddr", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("destAndNextMacAddr", handle_destAndNextMacAddr,
                               destAndNextMacAddr_oid, OID_LENGTH(destAndNextMacAddr_oid),
                               HANDLER_CAN_RONLY
        ));
}

int
handle_destAndNextMacAddr(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    FILE *fp;
    char dest_next_addr[250];
    char temp[250-20];
    char filename[128];
    char buf[30];
    char *s;

    memset(filename, 0, sizeof(filename));
    strcpy(filename, "/tmp/node.txt");
    memset(buf, 0, sizeof(buf)); 
    strcpy(buf, "DEST");
    memset(dest_next_addr, 0, sizeof(dest_next_addr));
    strcpy(dest_next_addr, "\nDEST ADDR               NEXT HOP\n");

    switch(reqinfo->mode) {

        case MODE_GET:

            if ((fp = fopen(filename, "r")) != NULL)
            {
                while(fgets(temp, sizeof(temp), fp) != NULL)
                {
                    /*Check if temp has buf*/
                    s = strstr(temp, buf);
                    if ( s != NULL)
                    {
                         break;
                    }
                }
                /*Check if temp has buf*/
                if (s != NULL)
                {
                      /*Read the last information*/
                    while(fgets(temp, sizeof(temp), fp) != NULL)
                    {
                         strcat(dest_next_addr, temp);

                    }

                    /*Remove the last '\n' in dest_next_addr*/
                    if (dest_next_addr[strlen(dest_next_addr) - 1] == '\n')
                    {
                         dest_next_addr[strlen(dest_next_addr) - 1] = '\0';
                    }  
                      
                    printf("%s\n", dest_next_addr);  
                }      
                fclose(fp);                     
            }
            else
            {
                perror("Can't open file");
            }


            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     dest_next_addr,
                                     strlen(dest_next_addr));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_destAndNextMacAddr\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
