/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef NODEIP_H
#define NODEIP_H

/* function declarations */
void init_nodeIp(void);
Netsnmp_Node_Handler handle_nodeIp;

#endif /* NODEIP_H */
