/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef NODEHOST_H
#define NODEHOST_H

/* function declarations */
void init_nodeHost(void);
Netsnmp_Node_Handler handle_nodeHost;

#endif /* NODEHOST_H */
