/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef WLANMACADRR_H
#define WLANMACADRR_H

/* function declarations */
void init_wlanMacAdrr(void);
Netsnmp_Node_Handler handle_wlanMacAdrr;

#endif /* WLANMACADRR_H */
